### ISSUE TITLE
Li ccECP 6Z bases are empty

### ISSUE THREAD

**Issue by mcbennet** [QMCPACK/pseudopotentiallibrary#107]
Hi all,

The Li ccECP 6Z basis sets are empty (see example below)

[recipes/Li/ccECP/Li.aug-cc-pV6Z.gaussian](https://github.com/QMCPACK/pseudopotentiallibrary/blob/main/recipes/Li/ccECP/Li.aug-cc-pV6Z.gamess)

All the best,

**Comment by prckent** [comment]
Good to hear from you Chandler. Sorry about that. Will discuss today. Likely we should add some automation to check the final files -- this is also a concern for updates such as #105 .

**Comment by aannabe** [comment]
I checked the paper with [accurate totals](https://pubs.acs.org/doi/10.1021/acs.jctc.9b00962), and the Li 6Z entry is empty. So, it seems we never optimized 6Z basis sets for Li. The empty files crept in because the neighbor Be does have 6Z (due to non-zero correlation energy). 

I will delete the Li 6Z in a PR. I checked for empty files and these are the only ones in the repo.
